-- AgentOS Migration 041: deZypher Appstore listing for native Studio install/open.
-- Additive data migration. Safe to rerun.

INSERT INTO agent_apps (
  id,
  workspace_id,
  name,
  slug,
  category,
  description,
  long_description,
  publisher_id,
  publisher_name,
  developer_handle,
  app_url,
  website_url,
  documentation_url,
  repository_url,
  device_targets,
  platforms,
  manifest,
  default_config,
  permissions_required,
  required_secrets,
  screenshots,
  keywords,
  tags,
  features,
  source,
  visibility,
  runtime_type,
  publish_state,
  health_status,
  endpoint_status,
  disabled,
  verified,
  published,
  spotlight,
  pricing,
  gallery,
  media_assets,
  release_notes,
  changelog,
  install_count,
  open_count,
  web_open_count,
  android_download_count,
  ios_download_count,
  download_count,
  active_user_count,
  rating,
  review_count,
  created_at,
  updated_at
) VALUES (
  '66f34c19-9e72-46b5-9819-887c3ae18b50',
  NULL,
  'deZypher',
  'dezypher',
  'Finance',
  'Open the deZypher spot experience from AgentOS.',
  'deZypher is the live spot experience linked from AgentOS. This listing lets Super AgentOS install and open the product through the governed Appstore path with execution records, approvals, and Library visibility.',
  'agentos_official',
  'AgentOS Labs',
  'agentos-labs',
  'https://dezypher.vercel.app/spot',
  'https://dezypher.vercel.app/spot',
  'https://dezypher.vercel.app/spot',
  'https://github.com/chrizzy-x/Agent-OS',
  '["AgentOS Cloud"]'::jsonb,
  '["web"]'::jsonb,
  '{
    "schemaVersion": "agentos.app.v1",
    "version": "1.0.0",
    "runtime": "external-app",
    "entrypoint": "https://dezypher.vercel.app/spot",
    "primitives": [],
    "skills": [],
    "requiredSkills": [],
    "bundledSkills": [],
    "permissions": [],
    "requiredSecrets": [],
    "commands": [
      { "name": "open", "description": "Open the deZypher spot experience." }
    ],
    "distribution": {
      "webUrl": "https://dezypher.vercel.app/spot"
    }
  }'::jsonb,
  '{"launchPath":"https://dezypher.vercel.app/spot"}'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '["dezypher","spot","finance"]'::jsonb,
  '["dezypher","spot","finance"]'::jsonb,
  '["Governed AgentOS launch","Appstore install record","Execution-backed open event"]'::jsonb,
  'internal',
  'public',
  'external-app',
  'published',
  'online',
  'healthy',
  FALSE,
  TRUE,
  TRUE,
  TRUE,
  '{"model":"free"}'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'Initial AgentOS Appstore listing.',
  '["Initial AgentOS Appstore listing."]'::jsonb,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  publisher_id = EXCLUDED.publisher_id,
  publisher_name = EXCLUDED.publisher_name,
  developer_handle = EXCLUDED.developer_handle,
  app_url = EXCLUDED.app_url,
  website_url = EXCLUDED.website_url,
  documentation_url = EXCLUDED.documentation_url,
  repository_url = EXCLUDED.repository_url,
  device_targets = EXCLUDED.device_targets,
  platforms = EXCLUDED.platforms,
  manifest = EXCLUDED.manifest,
  default_config = EXCLUDED.default_config,
  permissions_required = EXCLUDED.permissions_required,
  required_secrets = EXCLUDED.required_secrets,
  keywords = EXCLUDED.keywords,
  tags = EXCLUDED.tags,
  features = EXCLUDED.features,
  source = EXCLUDED.source,
  visibility = EXCLUDED.visibility,
  runtime_type = EXCLUDED.runtime_type,
  publish_state = EXCLUDED.publish_state,
  health_status = EXCLUDED.health_status,
  endpoint_status = EXCLUDED.endpoint_status,
  disabled = EXCLUDED.disabled,
  verified = EXCLUDED.verified,
  published = EXCLUDED.published,
  spotlight = EXCLUDED.spotlight,
  pricing = EXCLUDED.pricing,
  release_notes = EXCLUDED.release_notes,
  changelog = EXCLUDED.changelog,
  updated_at = NOW();

NOTIFY pgrst, 'reload schema';

-- ROLLBACK:
-- DELETE FROM agent_apps WHERE slug = 'dezypher';
